#!/bin/sh
set -ef +am
. /start/functions/fixConfigVars
. /start/functions/writeEnvironmentVars
. /start/functions/execCmd

if [ ! -e "/environment/vars" ]
then
   /bin/touch /environment/isFirstRun
   fixConfigVars
   writeEnvironmentVars
fi

execCmd "/start/stage2"
