#!/bin/sh
set -ef +am

if [ ! -e "/environment/vars" ]
then
   /bin/touch /environment/isFirstRun
   . /start/functions/fixConfigVars
   . /start/functions/writeEnvironmentVars
   fixConfigVars
   writeEnvironmentVars
else
   chmod g-rX /bin
   ln -sf /bin/busybox /bin/sh
fi
. /start/functions/execCmd
execCmd "/start/stage2"
