#!/bin/sh
set -e +a +m +s +i -f
. /start/functions/writeEnvironmentVars

if [ ! -e "/environment/vars" ]
then
   isFirstRun="true"
   writeEnvironmentVars
fi
exec /usr/bin/env -i /start/stage2 $isFirstRun
