#!/bin/sh
set -e +a +m +s +i -f
. /start/functions/writeEnvironmentVars
. /start/functions/execCmd

if [ ! -e "/environment/vars" ]
then
   /bin/touch /environment/isFirstRun
   writeEnvironmentVars
fi

execCmd "/start/stage2"
