#!/bin/sh
set -e +a +m +s +i -f
. /start/functions/writeEnvironmentVars
. /start/functions/execCmd

if [ ! -e "/environment/vars" ]
then
   isFirstRun="true"
   writeEnvironmentVars
fi

execCmd "/start/stage2 $isFirstRun"
