#!/usr/local/bin/dash
#set -e +a +m +s +i -f
. /stop/includeFunctions
PID=0
for sig in 1 2 3 6 9 14 15
do
   sig$PID=$sig
   trap "stop $(eval "echo sig$PID"); killpid $PID $(eval "echo sig$PID")" "$(eval "echo sig$PID")"
done
#set +e
