#!/bin/sh

startStage2(){
   set -e +a +m +s +i -f
   local -r IFS_bak=$IFS
   local VAR_FINAL_COMMAND
   . /start/stage2.functions
   . /environment/Vars
   if [ "$1" == "firstrun" ]
   then
      createLinuxUser
      updateSudoersConf
      fixHosts
      makeAllFromList "$(allVars noquote)"
      fixPermissionsForUsrLocalBin
   fi
   tryRunStage 3
   allVars quote > /environment/Vars
   execCmdAsLinuxUser $VAR_FINAL_COMMAND
}

startStage2 $1
