#!/bin/sh
set -e +a +m +s +i -f

# Set by shell:
# -------------------------------------------
# IFS


. /start/common.functions
. /start/stage2.functions

readonly ifs_bak=$IFS
echo "$IFS"
if [ "$(isFirstrun)" == "true" ]
then
echo readfirstrun
   #readFirstrunEnvironment
   . /environment/firstrun
   if [ -n "$VAR_CONFIG_DIR" ]
   then
      /bin/chown -R $VAR_LINUX_USER:root "$VAR_CONFIG_DIR"
      /bin/chmod 7770 "$VAR_CONFIG_DIR"
      if [ "$(ls -A "$VAR_CONFIG_DIR")" ]
      then
         set +f
         /bin/chmod -R ug=rw,o= "$VAR_CONFIG_DIR/"*
         set -f
      fi
   fi
   if [ -f "/start/stage3" ]
   then
   . /start/stage3
   fi
   echo timeforwrite
   writeRestartEnvironment
else
  # readRestartEnvironment
  . /environment/restart
   if [ -f "/start/stage3" ]
   then
   . /start/stage3
   fi
fi
executeCommandAsLinuxUser "$VAR_FINAL_COMMAND"
