#!/bin/sh
set -e +a +m +s +i -f

. /start/common.functions
. /start/stage1.functions
set
if [ "$(isSomethingToDo)" == "true" ]
then
   if [ "$(isFirstrun)" == "true" ]
   then
      createLinuxUser
      updateSudoersConf
      writeFirstrunEnvironment
      /bin/cat /environment/firstrun
   fi
   executeCommand /start/stage2
else
   echo "Nothing to do!"
fi
