#!/bin/sh
set -e +a +m +s +i -f

. /start/common.functions
. /start/stage1.functions

if [ "$(isSomethingToDo)" == "true" ]
then
   if [ "$(isFirstrun)" == "true" ]
   then
      createLinuxUser
      updateSudoersConf
      writeFirstrunEnvironment
   fi
   /bin/cat /environment/firstrun
   executeCommand /start/stage2
else
   echo "Nothing to do!"
fi
