#!/bin/sh
set -e +a +m +s +i -f

# Set by shell:
# -------------------------------------------
# IFS

# Passed from stage1:
# -------------------------------------------
# firstrun

. /start/stage2.functions

readonly ifs_bak=$IFS
if [ "$firstrun" == "true" ]
then
   readFirstrunEnvironment
   if [ -n "$VAR_CONFIG_DIR" ]
   then
      fixPermissionsForConfigDir
   fi
   fixPermissionsForUsrLocalBin
   tryRunStage 3
   writeRestartEnvironment
else
   readRestartEnvironment
   tryRunStage 3
fi
executeCommandAsLinuxUser "$VAR_FINAL_COMMAND"
