#!/bin/sh
set -e +a +m +s +i -f

writeEnvironmentVars(){
   local IFS=$(echo -en "\n\b")
   local tmp="$(set | grep -E "^VAR$2_")"
   local vars=""
   local delimiter=""
   for var in $tmp
   do
      vars="$vars$delimiter$var"
      delimiter=$'\n'
   done
   IFS=$(echo -en "")
   echo "$vars" > /environment/vars
}

if [ ! -e "/environment/vars" ]
then
   writeEnvironmentVars
   p="firstrun"
fi
exec /usr/bin/env -i /start/stage2 $p
